### PR TITLE
Use semilight font for Multiline textfield

### PR DESCRIPTION
**Pull request by lixonic**
related to #510

### CODE REVIEW

**Comment by mikewheaton** [comment]
In Fabric 3.0 we're introducing a new way of assigning font weights. Rather than having entirely different `font-family` names, we're using a common family variable of `$ms-font-family-base`. The `font-weight` property is set separately using one of these variables:

- `$ms-font-weight-light`
- `$ms-font-weight-regular`
- `$ms-font-weight-semilight`
- `$ms-font-weight-semibold`

Would you mind updating your PR to match this new pattern?

**Comment by lixonic** [comment]
@mikewheaton done 👍

**Comment by mikewheaton** [comment]
Approved! Thanks for the quick update here. No trouble getting the latest `master` to build?

**Comment by lixonic** [comment]
@mikewheaton  yep, https://monosnap.com/file/olY0WQC4cEMmPQKbjLWCiIIiAFWgtA

`npm install` solved the issue

**Comment by wdo3650** [comment]
@lixonic Can you add a newline to the bottom of the file you modified? The build linter is throwing a warning and preventing the initial build from finishing.

**Comment by mikewheaton** [comment]
@wdo3650 It doesn't look like he removed the newline from the end of TextField.scss, and it seems to build fine in Travis.

**Comment by wdo3650** [comment]
@mikewheaton sounds good. Let's merge this in and make sure to add the newline.

**Comment by wdo3650** [comment]
Approved.

**Comment by mikewheaton** [comment]
Thanks for merging this. I just pulled down the latest master (including this merge) and it builds without errors. Must have been a glitch with the linter you saw before.

**Pull request merged**
