### PR TITLE
Simplified DatePicker Markup

### PR DESCRIPTION
**Pull request by wdo3650**
Simplified markup by wrapping elements inside the JQuery plugin code.

### CODE REVIEW

**Comment by pbjorklund** [comment]
How are we supposed to set things like the input id now?

**Comment by pbjorklund** [comment]
Realized now that perhaps I can get a better answer by pinging @wdo3650 directly as it's a closed issue.

**Comment by wdo3650** [comment]
Thanks for the question. I assume you were you able to add id's to the input textfield before. In order to gain more information on what specifically you are looking for, can you describe what your process was and how you were using the id's?

**Comment by pbjorklund** [comment]
Well I liked being able to control the name and id of the input fields in order to handle posts and using js to do things with the fields. Not sure I understand your question :)

**Comment by wdo3650** [comment]
Thanks again for the bringing this up and it's a great question. PickaDate.js, which the DatePicker wraps, automatically assigns an id to the input textfield. I'm not sure how changing the id will affect the DatePicker's functionality. However, you can query the DOM to either set the id or get the id using JQuery. I would suggest getting the id as opposed to setting it in case changing the id interferes with functionality.

**Comment by wdo3650** [comment]
Thanks for sharing your concerns. See issue #71 where more details about near term changes to DatePicker can be found.

**Pull request merged**
