### PR TITLE
Fix Panel display bug

### PR DESCRIPTION
**Pull request by lixonic**
related to #511

### CODE REVIEW

**Comment by mikewheaton** [comment]
I suspect that this has been fixed in 3.0, but am unable to test as we don't have examples of `ms-Panel--left` and `ms-Panel--lightDismiss`. I'll add those in and submit a PR so we can see if this issue repros.

**Comment by mikewheaton** [comment]
Unable to repro because the left panel is currently broken. See issue #619.

**Comment by lixonic** [comment]
@mikewheaton  https://monosnap.com/file/kWnS0NuCNvAkLbw6UnNaBl7pclZ9vF 

same for `ms-Panel--lightDismiss`

**Comment by lixonic** [comment]
@mikewheaton i guess  this PR is irrelevant now.

**Comment by mikewheaton** [comment]
Yes, I think so. Thank you for submitting it though, we really appreciate all of your contributions lately!

**Pull request closed without merging**
