### PR TITLE
Fix: DatePicker on top of other DatePicker with correct z-index

### PR DESCRIPTION
**Pull request by casvaniersel**
This will fix the issue when two datepickers are used above each other. For example when using a start and end date.

### CODE REVIEW

**Comment by casvaniersel** [comment]
Thanks for the feedback. I've applied the suggested convention.

**Comment by wdo3650** [comment]
Awesome work! This is approved.

**Comment by ericthompson** [comment]
Hey @casvaniersel - thanks for contributing! Can you please sign the Contribution License Agreement located [here](https://cla.microsoft.com/)?

Thanks!

**Comment by casvaniersel** [comment]
Done!

Met vriendelijke groet / with kind regards,

Cas van Iersel
+31 (0)6 24 27 73 64 • +31 (0)88 420 42 42
cas@point42.nl<MAILTO:cas@point42.nl> • LinkedIn<http://www.linkedin.com/in/casvaniersel> • @casvaniersel<http://www.twitter.com/casvaniersel>



Van: Eric Thompson [mailto:notifications@github.com]
Verzonden: dinsdag 22 september 2015 01:49
Aan: OfficeDev/Office-UI-Fabric <Office-UI-Fabric@noreply.github.com>
CC: Cas van Iersel <cas@point42.nl>
Onderwerp: Re: [Office-UI-Fabric] Fix: DatePicker on top of other DatePicker with correct z-index (#111)


Hey @casvaniersel<https://github.com/casvaniersel> - thanks for contributing! Can you please sign the Contribution License Agreement located here<https://cla.microsoft.com/>?

Thanks!

**Comment by ericthompson** [comment]
Thanks, @casvaniersel!

**Pull request merged**
