### PR TITLE
Grid offset classes

### PR DESCRIPTION
**Pull request by estruyf**
There were no offset classes that enabled you to move the elements over the grid. I have added these grid offset utility classes to the SASS file. An example of how it can be used can be tested here: http://codepen.io/anon/pen/eJeyea

### CODE REVIEW

**Comment by mikewheaton** [comment]
Thanks for this pull request, @estruyf, but we actually do already have offset classes for the grid. They are 'push' and 'pull' classes and are available for all screen sizes. For example, `ms-u-mdPush12` and `ms-u-lgPull3`. Do these meet your needs?

**Comment by estruyf** [comment]
Hi @mikewheaton, you closed it a bit too fast :-). 

Offset and push/pull are not the same. Offset classes are setup with "margin-left" which will force other columns to move over the grid. It can be used to let all elements start from a specific point on the grid.

The push or pull classes are setup with "left" or "right", which does only position a specific element on which the push or pull class is defined. That also means that you could overlap some elements if you are not cautious.

I created another codepen to show you the difference: http://codepen.io/anon/pen/WrXaQm

**Comment by mikewheaton** [comment]
Thanks for the new CodePen, @estruyf – that makes it much clearer how offset differs from our current push/pull. It looks like both Foundation and Bootstrap provide these offset classes (increasing the left margin) in addition to push/pull for column ordering. I can see the value here, we'll just have to discuss as a team before merging the pull request.

**Comment by mikewheaton** [comment]
Looks good, thanks for contributing this!

**Pull request merged**
