### PR TITLE
Persona: update ms-Persona-imageArea

### PR DESCRIPTION
**Pull request by tomaon**

### CODE REVIEW

**Comment by mikewheaton** [comment]
Hi @tomaon, could you briefly describe the issue this pull request solves? We appreciate your contributions but can't merge them unless we understand the issues you are fixing.

**Comment by tomaon** [comment]
expected (= fixed): 
  screen shot 2016-01-29 at 12 01 15

actual:
screen shot 2016-01-29 at 12 00 21

**Comment by mikewheaton** [comment]
Thanks, that definitely looks like a bug and I don't see any issue with hiding `.ms-Persona-imageArea` entirely. One more review and we can merge this in.

**Comment by notandrew** [comment]
Yeah, it's probably better to use display: none for this.  
It's evident in this repro: Go to the persona card component test page and modify 'ms-Persona ms-Persona--sm' to 'ms-Persona ms-Persona--tiny'

Go ahead and merge.  :)

**Pull request merged**
