### PR TITLE
Wdo3650/beta/mdl2/commandbar

### PR DESCRIPTION
**Pull request by wdo3650**
MDL2-ified commandbar with color and behavior changes.

### CODE REVIEW

**Comment by mikewheaton** [comment]
Looks like there are some bug fixes in here. Are those specific to the new behaviors for the CommandBar, or something we should be getting fixed in Fabric 3.0 also?

**Comment by wdo3650** [comment]
@mikewheaton yeah, there are fixes for memory leaks. It would be ideal to get the memory leaks fixed in 3.0.

**Comment by mikewheaton** [comment]
@wdo3650 Could you make a quick PR to bring those changes into master, or is there more work involved because of the differences with the MDL2 command bar?

**Comment by mikewheaton** [comment]
The MDL2 icons aren't loading for me. Any ideas?

image

**Comment by wdo3650** [comment]
@mikewheaton the fixes might be a bit more involved. let's assign the bug to me and I can work on it.

**Comment by wdo3650** [comment]
Abandoning this PR. Will open another with SearchBox and CommandBar.

**Pull request closed without merging**
