### PR TITLE
Adding sample page for Language Overrides

### PR DESCRIPTION
**Pull request by notandrew**

### CODE REVIEW

**Comment by mikewheaton** [comment]
Nice work! My name is Mike Wheaton and I approved this pull request.

**Comment by notandrew** [comment]
:fireworks:

**Comment by mikewheaton** [comment]
After this gets approved, let's still leave the PR open and merge it into master once we have the other language-related issues fixed. Then we can release them together.

**Comment by philworthington** [comment]
Looking good, approved

**Comment by mikewheaton** [comment]
Marking this for Fabric 2.5.0 for now.

**Pull request closed without merging**
