### PR TITLE
Fix facepile bug in documentation

### PR DESCRIPTION
**Pull request by lixonic**
related to #634 

facepile

### CODE REVIEW

**Comment by mikewheaton** [comment]
Thanks, @lixonic! Let's get @philworthington to take a look as he was working on this most recently.

**Comment by mikewheaton** [comment]
@lixonic Could you merge 'master' back into your branch to update this PR?

**Comment by lixonic** [comment]
@mikewheaton this PR is irrelevant now. It is already fixed on master.

**Comment by mikewheaton** [comment]
Sorry we didn't get this merged in – your PR did fix at least part of the issues here.

**Pull request closed without merging**
