### PR TITLE
Add consistent spacing to README.md

### PR DESCRIPTION
**Pull request by mikewheaton**
This PR fixes a non-issue and is primarily to test PullApprove. 😄

### CODE REVIEW

**Comment by mikewheaton** [comment]
Approve

**Comment by mikewheaton** [comment]
Approved

**Comment by mikewheaton** [comment]
👍

**Comment by atneik** [comment]
Approve

**Comment by atneik** [comment]
Approved

**Comment by mikewheaton** [comment]
Abandoning this test PR. I guess we can just use the PullApprove interface to approve/reject a PR.

**Pull request closed without merging**
