### PR TITLE
Swap the color values for "orange light" and "orange lighter"

### LINKED ISSUE #350: Orange lighter is darker than orange light
Can we confirm that "orange lighter" is part of the official set of accent colors? It was added into Fabric at some point under the alert colors, and it just doesn't fit in.

image

### PR DESCRIPTION
**Pull request by mikewheaton**
Fixes #350.

### CODE REVIEW

**Comment by mikewheaton** [comment]
Submitted PR 13818 to our internal documentation repo. Don't merge this in until that PR has been merged.

**Comment by notandrew** [comment]
Looks great!

**Comment by philworthington** [comment]
Approved and we can close out the issue

**Comment by mikewheaton** [comment]
The PR has been approved and merged in for the docs site. Merging this one in.

**Pull request merged**
