### PR TITLE
Removes classes for icons that are no longer included with Fabric.

### LINKED ISSUE #79: Some icons are missing
Some icons are not shown in the sample page. For example ms-Icon--onedrive, ms-Icon--thumbDown, ms-Icon--thumbUp, ms-Icon--officeThreshold, ms-Icon--office365, ms-Icon--office365Preview, etc

### PR DESCRIPTION
**Pull request by mikewheaton**
Fixes #79

### CODE REVIEW

**Comment by notandrew** [comment]
Can you remove ms-Icon--classNotebook from the Icon sample page, too?  Thanks!

**Comment by mikewheaton** [comment]
Removed. There were also "space", "thumbsUp", and "thumbsDown" icons that are no longer in Fabric. Didn't we used to generate this page with JavaScript and the JSON file generated by Fontello? That would make it a lot easier to maintain. Right now we have 339 icon classes, and only 338 icons on the sample page. It would take ages to figure out what's missing...

**Comment by notandrew** [comment]
That's the plan -- we should have a workitem for that, together with auto-subsetting.

**Comment by mikewheaton** [comment]
Want to make a branch for everything MDL2 related and move these classes there for now? Right now the classes are in master, but I don't think we'll want them included in the next release.

**Pull request merged**
