### PR TITLE
Update color values

### LINKED ISSUE #471: Update theme colors and deprecate neutral secondary alt
The latest guidance from design means that we need to change:
- theme secondary from 2488d8 to 2b88d8
- theme tertiary from 69afe5 to 71afe5
- theme light from b3d6f2 to c7e0f4

Our "neutral secondary alt" color (#767676) also needs to be removed. Let's mark it as deprecated in 2.3.0 and then remove it in 3.0.0 using issue #470.

### PR DESCRIPTION
**Pull request by mikewheaton**
Fixes #471 

Documentation updates are required before merging this into master.

### CODE REVIEW

**Comment by Jahnp** [comment]
Looks great! Approved.

**Comment by notandrew** [comment]
Looks amazing! Approved :green_apple:

**Comment by mikewheaton** [comment]
Thanks for taking a look. I've submitted a PR to our documentation site repo. Once that's approved and merged in I'll merge this pull request.

**Comment by mikewheaton** [comment]
The PR for the documentation site has not been approved yet, but it's a simple change and I'm not expecting issues there. Will merge this in to include it in 2.3.0.

**Comment by mikewheaton** [comment]
The PR into the documentation site has been approved and merged. This change will be included in the next release.

**Pull request merged**
