### PR TITLE
Shifting language overrides to opt-in by default.

### PR DESCRIPTION
**Pull request by notandrew**

### CODE REVIEW

**Comment by mikewheaton** [comment]
Once this is approved, let's wait and merge the PR to master with other language-related PRs.

**Comment by Jahnp** [comment]
Agreed, this looks great. Consider it approved--except...

We should hold off on merging it in to master until we're ready for a major release, since this is a pretty significant breaking change from the default package. We should keep this and related branches up to date--or just merge all the language-related updates together--until the next major release is due. 

In the future, it could also be useful to consider adding a bundle definition matching the old output, e.g. fabric.css in addition to language overrides, or even standalone language overrides.

**Comment by mikewheaton** [comment]
Marking this for Fabric 2.5.0 for now.

**Comment by mikewheaton** [comment]
This is labeled 'needs-documentation'. What kind of documentation does it need?

**Comment by mikewheaton** [comment]
@notandrew: Is this PR still relevant, or does #486 address this?

**Pull request closed without merging**
