### PR TITLE
TextField: update z-index

### PR DESCRIPTION
**Pull request by tomaon**

### CODE REVIEW

**Comment by notandrew** [comment]
The change looks pretty straight-forward, but can you tell us the problem you're fixing? Thanks!

**Comment by mikewheaton** [comment]
Hi @tomaon, just checking in to see if you can provide us with some details on this pull request. What problem are you solving here?

**Comment by tomaon** [comment]
Same as #266, #294
Focuses label.ms-Label, not input.ms-TextField-field

**Comment by wdo3650** [comment]
If it's like #266 then I'm assuming the bug here is that ms-label is preventing a click event from occurring on the input field. 

This may have been fixed in master, as I can't seem to reproduce this bug.

**Comment by wdo3650** [comment]
@tomaon if I'm not mistaken this PR fixes an issue with the label preventing the caret from showing up in the input field on hover.  Nice work spotting the bug; however, the next release of Fabric, scheduled for later this week, switches over to Sass from Less. If you'd like you could file another PR with the Sass fix for this issue as Fabric will no longer be using Less.

**Comment by wdo3650** [comment]
#316 has been opened to address this issue.

**Pull request closed without merging**
