### PR TITLE
Merge 3.0.0 changes into master

### LINKED ISSUE #423: Disabled label is wrong color
There's no difference in the rendering of a disabled label vs. a regular label.  Is this right?

### PR DESCRIPTION
**Pull request by mikewheaton**
The time has come! This PR merges all of our early development work on 3.0.0 into the master branch, where we can continue to work on it as we prepare for the release.

Fixes #423, #428, #450, #452, #453, #466, #476, #479, #505, #512, #552, #320, #319, #310, #380, #398, #397, #403, and #416.

### CODE REVIEW

**Comment by Jahnp** [comment]
Approved

Amazing work, all!

**Comment by battletoilet** [comment]
Approved
We finally made it.

**Comment by andrewconnell** [comment]
WHOA... that's an epic list of commits & issues fixed. Congrats guys. You planning a post / writeup somewhere that explains what the big v2.x => v3.x changes are? We are close to a v1 release for ngOfficeUIFabric and want to work against the latest version of you guys so the timing is good. A writeup will help others (*see: us*) in taking a closer look on what we should keep an eye out for.

**Comment by ericthompson** [comment]
@andrewconnell - **yes!** we will be working on a big 'ol blog post that helps call out the changes and how some of the new work can be used. Definitely look forward to this in the near future!

**Comment by mikewheaton** [comment]
@andrewconnell: We're also planning to release Fabric 3.0 as a beta, and to provide a more detailed road map of the remaining items that we want to get in before it releases.

**Pull request merged**
